name: Flask Restful Swagger Test Suite

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run Black
      uses: lgeiger/black-action@master
      with:
        args: "--check -l 80 examples tests flask_restful_swagger"
    - name: Run Flake8
      uses: cclauss/GitHub-Action-for-Flake8@master
      with:
        args: "flake8 -v examples flask_restful_swagger"
    - name: Requirements
      run: |
        [[ -n "$(python --version 2>&1 | grep 2.7)" ]] && pip install mock
        pip install -r ./contributing/requirements/requirements-testing.txt
        python setup.py install
    - name: Security
      run: |
        safety check
        bandit -r flask_restful_swagger -c .bandit.rc
    - name: Test Suite
      run: |
        pytest --cov=. . --cov-fail-under=100
